### PR TITLE
Mutrino

### PR DESCRIPTION
**Pull request by amagela**
I made a "mutrino" branch to add the scripts necessary to build Nalu on Sandia Nat'l Labs' Mutrino. Currently, only the Haswell build is supported however I am working on the KNL build, too. Please let me know if you would like to add these to your repository.

### CODE REVIEW

**Comment by amagela** [comment]
Hello Jon:

Stefan and I looked and I am unable to generate a request for you to review (which is why he did it).

I built NetCDF the same way that you did for Cori. Ultimately, I started from your Cori config and kept hammering until it worked. I had to build other libraries one wouldn't normally need to (e.g., zlib) because these libraries were within "/usr" and when that is an "include" directory for Spack, it puts it into its list of include and lib directories and that caused all sorts of issues due to seemingly evil #include_next calls from the libs within "/usr." I have a thread with LLNL's Greg Becker and Greg Lee that goes through all of the little things we overcame for the Mutrino build if you are interested.

I am working on a KNL build right now but found a bug in Spack. They have a suggested fix for me to try (which I am about to try to move forward). When that is done I will likely submit another pull request for that system, too.

My motivation in sharing these scripts is to help the various people that may want to build/use Nalu on Trinity systems. This way, they only need to go to your repo rather than my own. Please let me know if you have any questions, comments, or concerns.

Kind regards,

Anthony M. Agelastos:
  Org.   = Scientific Applications & User Support, 9326;
  Loc.   = Sandia National Laboratories/ NM;
  Office = 505/284-5806;

**Comment by jrood-nrel** [comment]
Ok now I see that it's based on Cori because Mutrino is a Cray as well. So for full disclosure, my Cori configuration has received my least attention (sort of because I wanted so many packages external there, Spack felt like there was more configuration than just building Trilinos and Nalu), and I haven't looked at in months, which means I don't remember why I have a custom NetCDF there and that package file is probably pretty old now, so rather than conduct my own investigation, I just want to ask if you had given the latest NetCDF package file a try in Spack as well?

I would also be curious to browse the discussion about this build because I am interested about any Cray-specific issues that were found. I know Spack isn't so easy on Crays.

**Comment by amagela** [comment]
Hello Jon:

I can try the Spack NetCDF to see if that works better. Also, Greg Becker (CCd) mentioned that the workflow may be better if NaluSpack was set up as a Spack repo (e.g., `spack repo -h`) rather than running the script to patch and add to the Spack installation the extra Nalu items. Also, out of curiosity, do you have any plans to add your configurations into mainline Spack?


Kind regards,

Anthony M. Agelastos:
  Org.   = Scientific Applications & User Support, 9326;
  Loc.   = Sandia National Laboratories/ NM;
  Office = 505/284-5806;

**Comment by jrood-nrel** [comment]
@amagela I investigated this further and diffed this netcdf package file against the newest one and it doesn't seem to have changed at all, so I'm fine with this. It looks like I just had to comment out the `conflicts` statement for hdf5 for some reason. I would think the `packages.yaml` which has hdf5 set with `+mpi` would account for that, but I don't remember why it didn't. If I look at Cori again, I can try to resolve that but let's not worry about it right now.

I have looked into the `spack repo` command and it seems to be for controlling private package files on a local shared machine. If the local repository it creates can be separately stored into this git repository, and easily copied into a Spack installation on any machine, it might help with the few custom package files I keep here, but most of them are machine-specific and not package-specific, or I try to just do `sed` operations so that the customizations still work on the newest package files so I don't think it can really accomplish what this repo is currently doing which are mostly machine specific tasks. I will ask some other colleagues how they deal with the things I am using this repo for. Though a curated central repository for high profile machine-specific configurations would be nice.

I also do plan on trying to generalize some custom packages I have here to get into Spack itself, but something like the Catalyst IOSS adapter has been complicated to generalize. As far as the configurations go, I am not aware of any place in the main Spack repo they would be able to exist.

**Pull request merged**
